version: '1'
services:
  db:
    image: mysql:8.0.29
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=votingdb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
  backend:
    image: openjdk
    container_name: votingbk
    volumes:
      - .:/voting
    working_dir: /voting
    command: ./mvnw spring-boot:run
    environment:
      - MYSQL_HOST=db
      - RABBITMQ_HOST=mq
    ports:
      - 8080:8080
    depends_on:
      - db
      - mq